name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  setup:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - run: dotnet build
      working-directory: Test
    - name: Ensure is run
      run: dotnet run &
      working-directory: Test
    - name: Ensure is run
      run: dotnet build
      working-directory: TestProj
    - name: Install browsers
      run:  pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      working-directory: TestProj
    - name: Wait for the application to start
      run : xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' dotnet test
      working-directory: TestProj


        
        
          
        