name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - run: dotnet build
      working-directory: Test
    - name: Ensure is run
      run: dotnet run &
      working-directory: Test
    - name: Wait for the application to start
      uses: ./
      with:
        working-directory: Test
        start: dotnet -v
        run: dotnet -v
        wait-on: 'http://localhost:5093'
